export interface LogList {
	timestamp: number
	text: string
}

export const automationLogs = [
	'Navigating to homepage...',
	'Homepage loaded successfully.',
	"Clicking on 'Login' button...",
	'Login form displayed.',
	'Entering username...',
	'Username entered successfully.',
	'Entering password...',
	'Password entered successfully.',
	'Submitting login form...',
	'Login successful. Redirecting...',
	'Navigating to dashboard...',
	'Dashboard loaded successfully.',
	"Clicking on 'Profile' tab...",
	'Profile tab activated.',
	'Fetching user information...',
	'User information retrieved successfully.',
	"Clicking on 'Settings' button...",
	'Settings page loaded.',
	'Updating email address...',
	'Email address updated successfully.',
	'Updating profile picture...',
	'Profile picture updated successfully.',
	"Clicking on 'Save Changes' button...",
	'Changes saved successfully.',
	'Navigating back to dashboard...',
	'Dashboard reloaded.',
	'Logging out...',
	'Logout successful.',
	'Redirecting to homepage...',
	'Homepage reloaded.',
	"Clicking on 'Products' tab...",
	'Products tab selected.',
	"Searching for product 'XYZ'...",
	'Product found.',
	'Adding product to cart...',
	'Product added to cart successfully.',
	'Navigating to checkout...',
	'Checkout page loaded.',
	'Entering shipping details...',
	'Shipping details entered.',
	'Entering payment information...',
	'Payment information entered.',
	'Placing order...',
	'Order placed successfully.',
	'Order confirmation received.',
	'Logging out...',
	'Logout successful.',
	'Session ended. Closing browser.',
]
